export type GMEvent = {
	type: EVENT_TYPE | null;
	needNum: boolean;
	dynamicNum: boolean;
	num: string | null;
	name: string | null;
	fileName: string | null;
};

export const enum EVENT_TYPE {
	CREATE,
	DESTROY,
	ALARM,
	STEP,
	COLLISION,
	KEY_DOWN,
	MOUSE,
	OTHER,
	ASYNC = 7,
	DRAW,
	KEY_PRESS,
	KEY_RELEASE,
	CLEAN_UP = 12,
	GESTURE
};

export const EVENT = {
	// Alarm
	ALARM_0: 0, ALARM_1: 1, ALARM_2: 2, ALARM_3: 3,
	ALARM_4: 4, ALARM_5: 5, ALARM_6: 6, ALARM_7: 7,
	ALARM_8: 8, ALARM_9: 9, ALARM_10: 10, ALARM_11: 11,

	// General
	CLEAN_UP: 0, CREATE: 0, DESTROY: 0, DRAW: 0,
	DRAW_GUI: 64, WINDOW_RESIZE: 65,
	DRAW_BEGIN: 72, DRAW_END: 73, DRAW_GUI_BEGIN: 74, DRAW_GUI_END: 75,
	PREDRAW: 76, POSTDRAW: 77,

	// Gesture
	GESTURE_TAP: 0, GESTURE_DOUBLE_TAP: 1,
	GESTURE_DRAG_START: 2, GESTURE_DRAGGING: 3, GESTURE_DRAG_END: 4,
	GESTURE_FLICK: 5, GESTURE_PINCH_START: 6, GESTURE_PINCH_IN: 7,
	GESTURE_PINCH_OUT: 8, GESTURE_PINCH_END: 9,
	GESTURE_ROTATE_START: 10, GESTURE_ROTATING: 11, GESTURE_ROTATE_END: 12,
	GLOBAL_GESTURE_TAP: 64, GLOBAL_GESTURE_DOUBLE_TAP: 65,
	GLOBAL_GESTURE_DRAG_START: 66, GLOBAL_GESTURE_DRAGGING: 67, GLOBAL_GESTURE_DRAG_END: 68,
	GLOBAL_GESTURE_FLICK: 69, GLOBAL_GESTURE_PINCH_START: 70, GLOBAL_GESTURE_PINCH_IN: 71,
	GLOBAL_GESTURE_PINCH_OUT: 72, GLOBAL_GESTURE_PINCH_END: 73,
	GLOBAL_GESTURE_ROTATE_START: 74, GLOBAL_GESTURE_ROTATING: 75, GLOBAL_GESTURE_ROTATE_END: 76,

	// Keyboard
	KEYBOARD_NO_KEY: 0, KEYBOARD_ANY_KEY: 1,
	KEYBOARD_BACKSPACE: 8, KEYBOARD_TAB: 9, KEYBOARD_ENTER: 13,
	KEYBOARD_SHIFT: 16, KEYBOARD_CONTROL: 17, KEYBOARD_ALT: 18,
	KEYBOARD_ESCAPE: 27, KEYBOARD_SPACE: 32,
	KEYBOARD_PAGE_UP: 33, KEYBOARD_PAGE_DOWN: 34,
	KEYBOARD_END: 35, KEYBOARD_HOME: 36,
	KEYBOARD_LEFT: 37, KEYBOARD_UP: 38, KEYBOARD_RIGHT: 39, KEYBOARD_DOWN: 40,
	KEYBOARD_INSERT: 45, KEYBOARD_DELETE: 46,
	KEYBOARD_0: 48, KEYBOARD_1: 49, KEYBOARD_2: 50, KEYBOARD_3: 51, KEYBOARD_4: 52,
	KEYBOARD_5: 53, KEYBOARD_6: 54, KEYBOARD_7: 55, KEYBOARD_8: 56, KEYBOARD_9: 57,
	KEYBOARD_A: 65, KEYBOARD_B: 66, KEYBOARD_C: 67, KEYBOARD_D: 68, KEYBOARD_E: 69,
	KEYBOARD_F: 70, KEYBOARD_G: 71, KEYBOARD_H: 72, KEYBOARD_I: 73, KEYBOARD_J: 74,
	KEYBOARD_K: 75, KEYBOARD_L: 76, KEYBOARD_M: 77, KEYBOARD_N: 78, KEYBOARD_O: 79,
	KEYBOARD_P: 80, KEYBOARD_Q: 81, KEYBOARD_R: 82, KEYBOARD_S: 83, KEYBOARD_T: 84,
	KEYBOARD_U: 85, KEYBOARD_V: 86, KEYBOARD_W: 87, KEYBOARD_X: 88, KEYBOARD_Y: 89,
	KEYBOARD_Z: 90,
	KEYBOARD_NUMPAD_0: 96, KEYBOARD_NUMPAD_1: 97, KEYBOARD_NUMPAD_2: 98, KEYBOARD_NUMPAD_3: 99,
	KEYBOARD_NUMPAD_4: 100, KEYBOARD_NUMPAD_5: 101, KEYBOARD_NUMPAD_6: 102, KEYBOARD_NUMPAD_7: 103,
	KEYBOARD_NUMPAD_8: 104, KEYBOARD_NUMPAD_9: 105,
	KEYBOARD_NUMPAD_MULTIPLY: 106, KEYBOARD_NUMPAD_ADD: 107,
	KEYBOARD_NUMPAD_SUBTRACT: 109, KEYBOARD_NUMPAD_DECIMAL: 110, KEYBOARD_NUMPAD_DIVIDE: 111,
	KEYBOARD_F1: 112, KEYBOARD_F2: 113, KEYBOARD_F3: 114, KEYBOARD_F4: 115,
	KEYBOARD_F5: 116, KEYBOARD_F6: 117, KEYBOARD_F7: 118, KEYBOARD_F8: 119,
	KEYBOARD_F9: 120, KEYBOARD_F10: 121, KEYBOARD_F11: 122, KEYBOARD_F12: 123,

	// Mouse
	MOUSE_DOWN_LEFT: 0, MOUSE_DOWN_RIGHT: 1, MOUSE_DOWN_MIDDLE: 2,
	MOUSE_NO_BUTTON: 3, MOUSE_PRESS_LEFT: 4, MOUSE_PRESS_RIGHT: 5, MOUSE_PRESS_MIDDLE: 6,
	MOUSE_RELEASE_LEFT: 7, MOUSE_RELEASE_RIGHT: 8, MOUSE_RELEASE_MIDDLE: 9,
	MOUSE_ENTER: 10, MOUSE_LEAVE: 11,
	GLOBAL_MOUSE_DOWN_LEFT: 50, GLOBAL_MOUSE_DOWN_RIGHT: 51, GLOBAL_MOUSE_DOWN_MIDDLE: 52,
	GLOBAL_MOUSE_PRESS_LEFT: 53, GLOBAL_MOUSE_PRESS_RIGHT: 54, GLOBAL_MOUSE_PRESS_MIDDLE: 55,
	GLOBAL_MOUSE_RELEASE_LEFT: 56, GLOBAL_MOUSE_RELEASE_RIGHT: 57, GLOBAL_MOUSE_RELEASE_MIDDLE: 58,
	MOUSE_WHEEL_UP: 60, MOUSE_WHEEL_DOWN: 61,
	MOUSE_SCROLL_UP: 60, MOUSE_SCROLL_DOWN: 61,

	// Other
	OUTSIDE_ROOM: 0, INTERSECT_BOUNDARY: 1,
	GAME_START: 2, GAME_END: 3, ROOM_START: 4, ROOM_END: 5,
	ANIMATION_END: 7, PATH_END: 8,
	USER_EVENT_0: 10, USER_EVENT_1: 11, USER_EVENT_2: 12, USER_EVENT_3: 13,
	USER_EVENT_4: 14, USER_EVENT_5: 15, USER_EVENT_6: 16, USER_EVENT_7: 17,
	USER_EVENT_8: 18, USER_EVENT_9: 19, USER_EVENT_10: 20, USER_EVENT_11: 21,
	USER_EVENT_12: 22, USER_EVENT_13: 23, USER_EVENT_14: 24, USER_EVENT_15: 25,
	OUTSIDE_VIEW_0: 40, OUTSIDE_VIEW_1: 41, OUTSIDE_VIEW_2: 42, OUTSIDE_VIEW_3: 43,
	OUTSIDE_VIEW_4: 44, OUTSIDE_VIEW_5: 45, OUTSIDE_VIEW_6: 46, OUTSIDE_VIEW_7: 47,
	INTERSECT_VIEW_0_BOUNDARY: 50, INTERSECT_VIEW_1_BOUNDARY: 51,
	INTERSECT_VIEW_2_BOUNDARY: 52, INTERSECT_VIEW_3_BOUNDARY: 53,
	INTERSECT_VIEW_4_BOUNDARY: 54, INTERSECT_VIEW_5_BOUNDARY: 55,
	INTERSECT_VIEW_6_BOUNDARY: 56, INTERSECT_VIEW_7_BOUNDARY: 57,
	ANIMATION_UPDATE: 58, ANIMATION_EVENT: 59,

	// Async
	ASYNC_IMAGE_LOADED: 60, ASYNC_HTTP: 62, ASYNC_DIALOG: 63,
	ASYNC_IN_APP_PURCHASE: 66, ASYNC_CLOUD: 67, ASYNC_NETWORKING: 68,
	ASYNC_STEAM: 69, ASYNC_SOCIAL: 70, ASYNC_PUSH_NOTIFICATION: 71,
	ASYNC_SAVE_LOAD: 72, ASYNC_AUDIO_RECORDING: 73, ASYNC_AUDIO_PLAYBACK: 74,
	ASYNC_SYSTEM: 75, BROADCAST_MESSAGE: 76, WALLPAPER_SUBS_DATA: 81,

	// Step
	STEP: 0, STEP_BEGIN: 1, STEP_END: 2,
} as const;

export const EventName = {
	[EVENT_TYPE.CREATE]: "Create",
	[EVENT_TYPE.DESTROY]: "Destroy",
	[EVENT_TYPE.ALARM]: "Alarm",
	[EVENT_TYPE.STEP]: "Step",
	[EVENT_TYPE.COLLISION]: "Collision",
	[EVENT_TYPE.KEY_DOWN]: "Keyboard",
	[EVENT_TYPE.MOUSE]: "Mouse",
	[EVENT_TYPE.OTHER]: "Other",
	[EVENT_TYPE.DRAW]: "Draw",
	[EVENT_TYPE.KEY_PRESS]: "KeyPress",
	[EVENT_TYPE.KEY_RELEASE]: "KeyRelease",
	[EVENT_TYPE.CLEAN_UP]: "CleanUp",
	[EVENT_TYPE.GESTURE]: "Gesture"
} as const;

/*export const GMEvent = {
	create: "Create_0",
	destroy: "Destroy_0",
	cleanup: "CleanUp_0",
	step: "Step_0",
	stepbegin: "Step_1",
	stepend: "Step_2",
	
	alarm0: "Alarm_0",
	alarm1: "Alarm_1",
	alarm2: "Alarm_2",
	alarm3: "Alarm_3",
	alarm4: "Alarm_4",
	alarm5: "Alarm_5",
	alarm6: "Alarm_6",
	alarm7: "Alarm_7",
	alarm8: "Alarm_8",
	alarm9: "Alarm_9",
	alarm10: "Alarm_10",
	alarm11: "Alarm_11",

	draw: "Draw_0",
	drawgui: "Draw_64",
	windowresize: "Draw_65",
	drawbegin: "Draw_72",
	drawend: "Draw_73",
	drawguibegin: "Draw_74",
	drawguiend: "Draw_75",
	predraw: "Draw_76",
	postdraw: "Draw_77",

	tap: "Gesture_0",
	doubletap: "Gesture_1",
	dragstart: "Gesture_2",
	dragging: "Gesture_3",
	dragend: "Gesture_4",
	flick: "Gesture_5",
	pinchstart: "Gesture_6",
	pinchin: "Gesture_7",
	pinchout: "Gesture_8",
	pinchend: "Gesture_9",
	rotatestart: "Gesture_10",
	rotating: "Gesture_11",
	rotateend: "Gesture_12",
	globaltap: "Gesture_64",
	globaldoubletap: "Gesture_65",
	globaldragstart: "Gesture_66",
	globaldragging: "Gesture_67",
	globaldragend: "Gesture_68",
	globalflick: "Gesture_69",
	globalpinchstart: "Gesture_70",
	globalpinchin: "Gesture_71",
	globalpinchout: "Gesture_72",
	globalpinchend: "Gesture_73",
	globalrotatestart: "Gesture_74",
	globalrotating: "Gesture_75",
	globalrotateend: "Gesture_76",
} as const;*/
