export const CASSETTE_BACK_S1 = 1.70158;
export const CASSETTE_BACK_S2 = (CASSETTE_BACK_S1 * 1.525);
export const CASSETTE_BACK_C1 = CASSETTE_BACK_S1;
export const CASSETTE_BACK_C2 = CASSETTE_BACK_S2;
export const CASSETTE_BACK_C3 = (CASSETTE_BACK_S1 + 1);
